### ISSUE TITLE
parse can be tripped up by valid query string

### ISSUE THREAD

**Issue by nphoenix** [cawerkenthin/cmi5-AU-Simulator#4]
In my use case i had a fetch token of 
&fetch=https://localhost:62925/CMI5/listenForToken?token=5c882bf0-2c36-4275-81ab-fc34d6bdb5c3

but inside of parse function 
if (tmp[0].toUpperCase() === val) result = decodeURIComponent(tmp[1]);  

was losing my =5c882bf0-2c36-4275-81ab-fc34d6bdb5c3

So this edit will solve:
if (tmp[0].toUpperCase() === val) result = decodeURIComponent(item.slice((-1 * (item.length - item.indexOf("=")-1))));

**Comment by cawerkenthin** [comment]
Thanks, resolved.
